### ISSUE TITLE
Resolving completion triggers an error

### ISSUE THREAD

**Issue by rchl** [python-lsp/python-lsp-server#123]
v1.3.2

1. Install `pygame` and ensure pylsp is aware of it.
2. Write:
```py
import pygame as pg

pg.display.set_mo
```
3. Place cursor after `set_mo` and trigger completion.
4. Complete the `set_mode()` completion.

Logs:

`completionItem/resolve`

```
{
  "data": {
    "doc_uri": "file:///Users/rafal/workspace/github/python-lsp-server/test/__init__.py"
  },
  "insertText": "set_mode()",
  "kind": 3,
  "label": "set_mode(size, flags, depth, display, vsync)",
  "sortText": "aset_mode"
}
```

```
{
  "code": -32602,
  "data": {
    "traceback": [
      "  File \"/../LSP-pylsp/lib/python3.9/site-packages/pylsp_jsonrpc/endpoint.py\", line 116, in consume\n    self._handle_request(message['id'], message['method'], message.get('params'))\n",
      "  File \"/../LSP-pylsp/lib/python3.9/site-packages/pylsp_jsonrpc/endpoint.py\", line 185, in _handle_request\n    handler_result = handler(params)\n",
      "  File \"/../LSP-pylsp/lib/python3.9/site-packages/pylsp_jsonrpc/dispatchers.py\", line 25, in handler\n    return method(**(params or {}))\n",
      "  File \"/../LSP-pylsp/lib/python3.9/site-packages/pylsp/python_lsp.py\", line 318, in m_completion_item__resolve\n    return self.completion_item_resolve(completionItem)\n",
      "  File \"/../LSP-pylsp/lib/python3.9/site-packages/pylsp/python_lsp.py\", line 269, in completion_item_resolve\n    return self._hook('pylsp_completion_item_resolve', doc_uri, completion_item=completion_item)\n",
      "  File \"/../LSP-pylsp/lib/python3.9/site-packages/pylsp/python_lsp.py\", line 156, in _hook\n    return hook_handlers(config=self.config, workspace=workspace, document=doc, **kwargs)\n",
      "  File \"/../LSP-pylsp/lib/python3.9/site-packages/pluggy/_hooks.py\", line 265, in __call__\n    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)\n",
      "  File \"/../LSP-pylsp/lib/python3.9/site-packages/pluggy/_manager.py\", line 80, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n",
      "  File \"/../LSP-pylsp/lib/python3.9/site-packages/pluggy/_manager.py\", line 327, in traced_hookexec\n    return outcome.get_result()\n",
      "  File \"/../LSP-pylsp/lib/python3.9/site-packages/pluggy/_result.py\", line 60, in get_result\n    raise ex[1].with_traceback(ex[2])\n",
      "  File \"/../LSP-pylsp/lib/python3.9/site-packages/pluggy/_result.py\", line 33, in from_call\n    result = func()\n",
      "  File \"/../LSP-pylsp/lib/python3.9/site-packages/pluggy/_manager.py\", line 324, in <lambda>\n    lambda: oldcall(hook_name, hook_impls, kwargs, firstresult)\n",
      "  File \"/../LSP-pylsp/lib/python3.9/site-packages/pluggy/_callers.py\", line 60, in _multicall\n    return outcome.get_result()\n",
      "  File \"/../LSP-pylsp/lib/python3.9/site-packages/pluggy/_result.py\", line 60, in get_result\n    raise ex[1].with_traceback(ex[2])\n",
      "  File \"/../LSP-pylsp/lib/python3.9/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n",
      "  File \"/../LSP-pylsp/lib/python3.9/site-packages/pylsp/plugins/rope_completion.py\", line 86, in pylsp_completion_item_resolve\n    completion, data = document.shared_data['LAST_ROPE_COMPLETIONS'].get(completion_item['label'])\n"
    ]
  },
  "message": "TypeError: cannot unpack non-iterable NoneType object"
}
```

**Comment by rchl** [comment]
Also this is probably unrelated issue but the completion inserts a plain `set_mode()` text which results in the cursor being positioned after `()`. This is not really expected by users. It should either not insert `()` or use a snippet with cursor positioned between `()`.

**Comment by rchl** [comment]
I've noticed now that there is a `pylsp.plugins.jedi_completion.include_params` setting to disable the parameters (parenthesis). That sort of solves that second issue although I would expect the completions with parenthesis to work better anyway.

**Comment by captain0xff** [comment]
Just now noticed that ```import py``` and then autocompleting to pygame also causes a similar error. And yes its the same for every external module.

**Comment by rchl** [comment]
That could be the issue that was just fixed in 1.3.2.

**Comment by captain0xff** [comment]
Not sure if I did everything correctly but I built python-lsp-server from source but both the errors are still there.
